- name: github-test123
  production: false
  servicePlan: F1
  platform:
    dbProvider: AzureSQL Database
    imageRepository: virtopaasregistrymain.azurecr.io/saas/platform
    imageTag: latest-stable
    sqlReplica: false
    redis:
      service: redis-prod-vc02-redis-cluster.redis-cluster:6379
    config:
      PushNotifications__ScalabilityMode: None
      Search__Provider: ElasticSearch8
      APPINSIGHTS_INSTRUMENTATIONKEY: 66138ce0-e52f-4a8a-a6e3-aed0f0a2a0f8
  storefront:
    enabled: false
    config:
      VirtoCommerce__DefaultStore: B2B-store
      VirtoCommerce__Endpoint__Password: store
      Swagger__UI__Enable: true
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      DOTNET_USE_POLLING_FILE_WATCHER: true
    themes:
      B2B-store: https://github.com/VirtoCommerce/vc-frontend/releases/download/2.36.0/vc-theme-b2b-vue-2.36.0.zip
  customApps:
    app1:
      enabled: false
    app2:
      enabled: false
  routes:
  - host: github-test123-storefront.govirto.com
    root: B2B-store
    paths:
    - path: /xapi
      route: platform
    - path: /files
      route: platform
    - path: /connect/token
      route: platform
    - path: /graphql
      route: platform
    - path: /revoke/token
      route: platform
    - path: /api/files
      route: platform
  version: 3.240
