- name: almaty-cool
  production: false
  servicePlan: B1
  platform:
    dbProvider: AzureSQL Database
    imageRepository: virtopaasregistrymain.azurecr.io/saas/platform
    imageTag: latest-stable
    sqlReplica: false
    redis:
      service: redis-dev-vc01-redis-cluster.redis-cluster:6379
    config:
      APPINSIGHTS_INSTRUMENTATIONKEY: a2d5234e-7f26-43d2-b34d-a0d5e607fcd0
  storefront:
    imageRepository: ghcr.io/virtocommerce/storefront
    imageTag: 6.24.0-alpha.962-pt-12422-bbc13210
    config:
      APPINSIGHTS_INSTRUMENTATIONKEY: 76855c9b-9383-453f-81e5-3e48c19c3715
    themes:
      B2B-store: https://github.com/VirtoCommerce/vc-frontend/releases/download/2.42.0/vc-theme-b2b-vue-2.41.0.zip
  customApps:
    app1:
      enabled: false
    app2:
      enabled: false
  routes:
  - host: almaty-cool-storefront.virtocloud.dev
    root: B2B-store
    ssl: true
    paths:
    - path: /xapi
      route: platform
    - path: /files
      route: platform
    - path: /connect/token
      route: platform
    - path: /graphql
      route: platform
    - path: /revoke/token
      route: platform
    - path: /api/files
      route: platform
  version: 3.238